### ISSUE TITLE
Instructions need updating to include production secrets so build doesn't fail.

### ISSUE THREAD

**Issue by janyk** [arcticShadow/cognito-openid-connect-provider-angular#1]
Following the instructions, the builds on first pass due to a compile error, regardless of environment.

Maybe the docs need to include intializing the `secrets.prod.ts` file too.

**Comment by ColeTMNZ** [comment]
This is an example app, and as such should not be built for production. I feel its fair to keep it broken for production - to encourage users to not use it :-)
